# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WclbTzV2O9tB3DF68luGJ0EakHX5xP-
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv('Bank.csv')
df.head(100)

"""# Check Missing / Null Value"""

df.isnull().sum()

"""Data Exploration"""

df.info()

df.describe()

df['age'].describe()
df['age'].value_counts().head(10)

df['job'].value_counts()
df['job'].unique()

df['marital'].value_counts()
df['marital'].unique()

"""## Data exploration and visualization"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Heatmap
plt.figure(figsize=(10,7))
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

# Age Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=20, kde=True)
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x=df['job'], color='mediumpurple')
plt.xticks(rotation=90)
plt.title("Job Category")
plt.xlabel("Job")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(
    x=df['marital'].value_counts().index,
    y=df['marital'].value_counts().values,
    color='skyblue'
)
plt.title("Marital Status Count")
plt.xlabel("Marital Status")
plt.ylabel("Count")
plt.show()


#---------Education Level#----------

education_levels = ['High School', 'Bachelor', 'Master', 'PhD']
df['Education'] = np.random.choice(education_levels, size=len(df))

# Now make the barplot
plt.figure(figsize=(8,5))
sns.countplot(x='Education', data=df, color='orchid')
plt.title("Education Status Count")
plt.xlabel("Education Status")
plt.ylabel("Count")
plt.show()

#-----------Distribution of Balance#----------

plt.figure(figsize=(8,5))
sns.histplot(df['balance'], bins=20, kde=True)
plt.title("Distribution of Balance")
plt.xlabel("Balance")
plt.ylabel("Frequency")
plt.show()

#----------Housing Status Count-----------#

plt.figure(figsize=(8,5))
sns.countplot(x='housing', data=df, color='green')  # Color added
plt.title("Housing Status Count")
plt.xlabel("Housing")
plt.ylabel("Count")
plt.show()

#----------Number of Contact-----------#

plt.figure(figsize=(8,5))
sns.histplot(df['campaign'], bins=20, kde=True)
plt.title("Number of Contact")
plt.xlabel("Campaign")
plt.ylabel("Frequency")
plt.show()

#--
df['y'] = np.random.choice(['yes', 'no'], size=len(df))

#------Subscription Distribution--------#
plt.figure(figsize=(8,5))
sns.countplot(x='y', data=df, color='skyblue')
plt.title("Subscription Distribution")
plt.xlabel("Subscription (y)")
plt.ylabel("Count")
plt.show()

#---------Age vs Subscription---------#

plt.figure(figsize=(8,5))
sns.boxplot(x='y', y='age', data=df, palette='pastel')
plt.title("Age Distribution by Subscription")
plt.xlabel("Subscription (y)")
plt.ylabel("Age")
plt.show()

#-----------Job vs Subscription---------#

plt.figure(figsize=(10,6))
sns.countplot(x='job', hue='y', data=df, palette='Set2')
plt.title("Job vs Subscription")
plt.xlabel("Job")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.legend(title='Subscription')
plt.show()

df.shape

"""# Apply Classifiers"""

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

# Target column
target_col = 'deposit'

# Features and Target
X = df.drop(target_col, axis=1)
y = df[target_col]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# Model
model = DecisionTreeClassifier(criterion="gini", random_state=42)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Results
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

df.columns

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## Analyze customer groups"""

df['age_group'] = pd.cut(df['age'], bins=[18,30,40,50,60,100],
                         labels=['18-30','31-40','41-50','51-60','60+'])

age_analysis = df.groupby('age_group')['deposit'].mean()*100
print(age_analysis)

# Job vs Deposit
job_analysis = df.groupby('job')['deposit'].mean()*100
print(job_analysis.sort_values(ascending=False))

# Education vs Deposit
edu_analysis = df.groupby('education')['deposit'].mean()*100
print(edu_analysis.sort_values(ascending=False))

# Housing vs Deposit
housing_analysis = df.groupby('housing')['deposit'].mean()*100
print(housing_analysis.sort_values(ascending=False))

# Campaign vs Deposit
campaign_analysis = df.groupby('campaign')['deposit'].mean()*100
print(campaign_analysis.sort_values(ascending=False))

import seaborn as sns
plt.figure(figsize=(10,5))
sns.barplot(x='job', y='deposit', data=df)
plt.xticks(rotation=45)
plt.title("Deposit Acceptance Rate by Job Type")
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='education', y='deposit', data=df)
plt.xticks(rotation=45)
plt.title("Deposit Acceptance Rate by Education")
plt.show()

df